---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  labels:
    app: udagram-reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-reverseproxy
  template:
    metadata:
      labels:
        app: udagram-reverseproxy
    spec:
      containers:
      - image: diesermarkus/udagram-reverseproxy:v1
        name: udagram-reverseproxy
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1024Mi"
            cpu: "600m"
        ports:
        - containerPort: 8080
      restartPolicy: Always