sudo: required
language: python
services:
- docker

script:
# Build
- docker build -t udagram-reverseproxy ./project/udagram-reverseproxy
- docker build -t udagram-api-feed ./project/udagram-api-feed
- docker build -t udagram-api-user ./project/udagram-api-user
- docker build -t udagram-frontend ./project/udagram-frontend

# Tagging
- docker tag udagram-reverseproxy diesermarkus/udagram-reverseproxy:v1
- docker tag udagram-api-feed diesermarkus/udagram-api-feed:v1
- docker tag udagram-api-user diesermarkus/udagram-api-user:v1
- docker tag udagram-frontend diesermarkus/udagram-frontend:v1

# Push
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push diesermarkus/udagram-reverseproxy:v1
- docker push diesermarkus/udagram-api-feed:v1
- docker push diesermarkus/udagram-api-user:v1
- docker push diesermarkus/udagram-frontend:v1