# Build
- docker build -t reverseproxy ./reverseproxy
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend

# Tagging
- docker tag reverseproxy diesermarkus/reverseproxy:v1
- docker tag udagram-api-feed diesermarkus/udagram-api-feed:v1
- docker tag udagram-api-user diesermarkus/udagram-api-user:v1
- docker tag udagram-frontend diesermarkus/udagram-frontend:v1

# Push
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push sudkul/udagram-api-feed:v1